### ISSUE TITLE
Unable to run elastic pass

### ISSUE THREAD

**Issue by yrq0208** [lana555/dynamatic#3]
Hi all,

I encountered an error when trying to run elastic pass. When I run "make name=loop_array graph" I have this,

![Screenshot from 2020-09-03 11-07-37](https://user-images.githubusercontent.com/34848593/92101903-b5139d80-edd5-11ea-9243-d9cfd7474f61.png)

The error seems to be "Error: dot: can't open _build/loop_array/*_graph.dot"?

I wonder has anyone encountered something similar before?

Thanks in advance.

**Comment by lana555** [comment]
Hi, 

are you running the code in the Dynamatic VM or in your own environment? If the second, the problem might be the way you are building LLVM. You could try to build LLVM in CMake Debug mode (instead of CMake RelWithDebugInfo). I remember that it fixed the same issue for some people. 

Lana

**Comment by yrq0208** [comment]
Hi Lana,

Thanks for your reply. Building LLVM in CMake Debug mode works for me.
